[unix_http_server]
file=/tmp/supervisor.sock

[supervisord]
nodaemon=true
logfile=./data/supervisord.log
pidfile=/tmp/supervisord.pid

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:cron]
command=cron -f
autostart=true
autorestart=true

[program:webapp]
command=python3 app.py
autostart=true
autorestart=true

[program:ser2net]
command=ser2net -n -c ./data/ser2net.yaml
autostart=true
autorestart=true

[program:ttyd]
command=ttyd -p 7000 telnet 127.0.0.1 6666
autostart=true
autorestart=true